version: '3.8'

services:
  my_service:
    image: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "2222:22"
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    command: /bin/bash
